/* ═══════════════════════════════════════════════════════════════
   EDGE Global Solutions — 6-Language Translation Dictionary
   Languages: EN, FR, ES, AR, TR, FA
   ═══════════════════════════════════════════════════════════════ */

const translations = {
// ─────────────────────────────────────────────────────────────
// NAVIGATION
// ─────────────────────────────────────────────────────────────
nav_services: { en:"Services", fr:"Services", es:"Servicios", ar:"الخدمات", tr:"Hizmetler", fa:"خدمات" },
nav_solutions: { en:"Solutions", fr:"Solutions", es:"Soluciones", ar:"الحلول", tr:"Çözümler", fa:"راه‌حل‌ها" },
nav_markets: { en:"Markets", fr:"Marchés", es:"Mercados", ar:"الأسواق", tr:"Pazarlar", fa:"بازارها" },
nav_why: { en:"Why Us", fr:"Pourquoi Nous", es:"Por Qué Nosotros", ar:"لماذا نحن", tr:"Neden Biz", fa:"چرا ما" },
nav_contact: { en:"Contact", fr:"Contact", es:"Contacto", ar:"اتصل بنا", tr:"İletişim", fa:"تماس" },

// ─────────────────────────────────────────────────────────────
// HERO SECTION
// ─────────────────────────────────────────────────────────────
hero_badge: {
    en:"AI-Powered Global Solutions",
    fr:"Solutions Mondiales Propulsées par l'IA",
    es:"Soluciones Globales Impulsadas por IA",
    ar:"حلول عالمية مدعومة بالذكاء الاصطناعي",
    tr:"Yapay Zeka Destekli Küresel Çözümler",
    fa:"راه‌حل‌های جهانی مبتنی بر هوش مصنوعی"
},
hero_title: {
    en:'Intelligent <span class="gradient-text">Automation</span> for a Connected World',
    fr:'<span class="gradient-text">Automatisation</span> Intelligente pour un Monde Connecté',
    es:'<span class="gradient-text">Automatización</span> Inteligente para un Mundo Conectado',
    ar:'<span class="gradient-text">أتمتة ذكية</span> لعالم متصل',
    tr:'Bağlı Bir Dünya için Akıllı <span class="gradient-text">Otomasyon</span>',
    fa:'<span class="gradient-text">اتوماسیون هوشمند</span> برای جهانی متصل'
},
hero_sub: {
    en:"We combine artificial intelligence, drone technology, advanced sensors and autonomous agents to deliver cutting-edge solutions across energy, agriculture, healthcare, tourism, and industrial automation.",
    fr:"Nous combinons l'intelligence artificielle, la technologie de drones, des capteurs avancés et des agents autonomes pour fournir des solutions de pointe dans l'énergie, l'agriculture, la santé, le tourisme et l'automatisation industrielle.",
    es:"Combinamos inteligencia artificial, tecnología de drones, sensores avanzados y agentes autónomos para ofrecer soluciones de vanguardia en energía, agricultura, salud, turismo y automatización industrial.",
    ar:"نجمع بين الذكاء الاصطناعي وتقنيات الطائرات بدون طيار وأجهزة الاستشعار المتقدمة والوكلاء المستقلين لتقديم حلول متطورة في مجالات الطاقة والزراعة والرعاية الصحية والسياحة والأتمتة الصناعية.",
    tr:"Yapay zeka, drone teknolojisi, gelişmiş sensörler ve otonom ajanları birleştirerek enerji, tarım, sağlık, turizm ve endüstriyel otomasyon alanında en son teknoloji çözümler sunuyoruz.",
    fa:"ما هوش مصنوعی، فناوری پهپاد، حسگرهای پیشرفته و عامل‌های خودمختار را ترکیب می‌کنیم تا راه‌حل‌های پیشرفته‌ای در حوزه‌های انرژی، کشاورزی، بهداشت و درمان، گردشگری و اتوماسیون صنعتی ارائه دهیم."
},
hero_cta: { en:"Get Started", fr:"Commencer", es:"Comenzar", ar:"ابدأ الآن", tr:"Başlayın", fa:"شروع کنید" },
hero_cta2: { en:"Explore Services", fr:"Découvrir les Services", es:"Explorar Servicios", ar:"استكشف الخدمات", tr:"Hizmetleri Keşfedin", fa:"خدمات را کشف کنید" },
stat_areas: { en:"Service Areas", fr:"Domaines de Service", es:"Áreas de Servicio", ar:"مجالات الخدمة", tr:"Hizmet Alanları", fa:"حوزه‌های خدماتی" },
stat_regions: { en:"Continental Regions", fr:"Régions Continentales", es:"Regiones Continentales", ar:"مناطق قارية", tr:"Kıtasal Bölgeler", fa:"مناطق قاره‌ای" },
stat_solutions: { en:"Solution Modules", fr:"Modules de Solution", es:"Módulos de Solución", ar:"وحدات الحلول", tr:"Çözüm Modülleri", fa:"ماژول‌های راه‌حل" },
stat_agents: { en:"Autonomous Agents", fr:"Agents Autonomes", es:"Agentes Autónomos", ar:"وكلاء مستقلون", tr:"Otonom Ajanlar", fa:"عامل‌های خودمختار" },

// ─────────────────────────────────────────────────────────────
// SERVICES OVERVIEW (10 cards)
// ─────────────────────────────────────────────────────────────
svc_tag: { en:"What We Do", fr:"Ce Que Nous Faisons", es:"Lo Que Hacemos", ar:"ما نفعله", tr:"Ne Yapıyoruz", fa:"چه می‌کنیم" },
svc_title: { en:"Ten Pillars of Intelligent Service", fr:"Dix Piliers du Service Intelligent", es:"Diez Pilares del Servicio Inteligente", ar:"أعمدة الخدمة الذكية العشرة", tr:"Akıllı Hizmetin On Sütunu", fa:"ده ستون خدمات هوشمند" },
svc_sub: { en:"From solar panel inspection to AI-powered healthcare platforms — one technology stack, endless applications.", fr:"De l'inspection de panneaux solaires aux plateformes de santé alimentées par l'IA — une pile technologique, des applications infinies.", es:"Desde la inspección de paneles solares hasta plataformas de salud impulsadas por IA — una pila tecnológica, aplicaciones infinitas.", ar:"من فحص الألواح الشمسية إلى منصات الرعاية الصحية المدعومة بالذكاء الاصطناعي — تقنية واحدة، تطبيقات لا حصر لها.", tr:"Güneş paneli denetiminden yapay zeka destekli sağlık platformlarına — tek bir teknoloji yığını, sonsuz uygulama.", fa:"از بازرسی پنل‌های خورشیدی تا پلتفرم‌های بهداشتی مبتنی بر هوش مصنوعی — یک پشته فناوری، کاربردهای بی‌پایان." },

svc1_title: { en:"Solar Energy Services", fr:"Services d'Énergie Solaire", es:"Servicios de Energía Solar", ar:"خدمات الطاقة الشمسية", tr:"Güneş Enerjisi Hizmetleri", fa:"خدمات انرژی خورشیدی" },
svc1_desc: { en:"Thermal drone inspection, panel cleaning, performance monitoring, and degradation analytics for solar farms and rooftops.", fr:"Inspection par drone thermique, nettoyage de panneaux, surveillance des performances et analyse de dégradation pour fermes solaires et toitures.", es:"Inspección con dron térmico, limpieza de paneles, monitoreo de rendimiento y análisis de degradación para granjas solares y techos.", ar:"فحص بالطائرات بدون طيار حرارية، تنظيف الألواح، مراقبة الأداء، وتحليل التدهور للمزارع الشمسية والأسطح.", tr:"Termal drone denetimi, panel temizliği, performans izleme ve güneş çiftlikleri için bozulma analitiği.", fa:"بازرسی حرارتی با پهپاد، تمیز کردن پنل‌ها، نظارت بر عملکرد و تحلیل تخریب برای مزارع خورشیدی و پشت‌بام‌ها." },

svc2_title: { en:"Infrastructure Inspection", fr:"Inspection d'Infrastructure", es:"Inspección de Infraestructura", ar:"فحص البنية التحتية", tr:"Altyapı Denetimi", fa:"بازرسی زیرساخت" },
svc2_desc: { en:"Bridge surveys, building heat-loss analysis, construction monitoring, and pipeline corridor assessment via aerial thermal imaging.", fr:"Relevés de ponts, analyse des pertes de chaleur des bâtiments, surveillance de construction et évaluation de corridors de pipelines par imagerie thermique aérienne.", es:"Estudios de puentes, análisis de pérdida de calor en edificios, monitoreo de construcción y evaluación de corredores de tuberías mediante imagen térmica aérea.", ar:"مسوح الجسور، تحليل فقدان الحرارة في المباني، مراقبة البناء، وتقييم ممرات الأنابيب عبر التصوير الحراري الجوي.", tr:"Köprü araştırmaları, bina ısı kaybı analizi, inşaat izleme ve hava termal görüntüleme ile boru hattı koridoru değerlendirmesi.", fa:"بررسی پل‌ها، تحلیل اتلاف حرارت ساختمان، نظارت بر ساخت و ارزیابی کریدور خطوط لوله از طریق تصویربرداری حرارتی هوایی." },

svc3_title: { en:"Precision Agriculture", fr:"Agriculture de Précision", es:"Agricultura de Precisión", ar:"الزراعة الدقيقة", tr:"Hassas Tarım", fa:"کشاورزی دقیق" },
svc3_desc: { en:"NDVI crop health mapping, irrigation optimization, soil moisture analysis, pest detection, and livestock thermal monitoring.", fr:"Cartographie de la santé des cultures NDVI, optimisation de l'irrigation, analyse de l'humidité du sol, détection des parasites et surveillance thermique du bétail.", es:"Mapeo de salud de cultivos NDVI, optimización de riego, análisis de humedad del suelo, detección de plagas y monitoreo térmico de ganado.", ar:"رسم خرائط صحة المحاصيل NDVI، تحسين الري، تحليل رطوبة التربة، اكتشاف الآفات، والمراقبة الحرارية للماشية.", tr:"NDVI ürün sağlığı haritalama, sulama optimizasyonu, toprak nemi analizi, zararlı tespiti ve hayvan termal izleme.", fa:"نقشه‌برداری سلامت محصول NDVI، بهینه‌سازی آبیاری، تحلیل رطوبت خاک، شناسایی آفات و نظارت حرارتی دام." },

svc4_title: { en:"Healthcare & Medical Tech", fr:"Santé & Technologie Médicale", es:"Salud y Tecnología Médicale", ar:"الرعاية الصحية والتقنية الطبية", tr:"Sağlık ve Tıp Teknolojisi", fa:"بهداشت و فناوری پزشکی" },
svc4_desc: { en:"Telemedicine platforms, patient management AI, medical tourism booking, thermal screening systems, and health camp coordination.", fr:"Plateformes de télémédecine, IA de gestion des patients, réservation de tourisme médical, systèmes de dépistage thermique et coordination de camps de santé.", es:"Plataformas de telemedicina, IA de gestión de pacientes, reservas de turismo médico, sistemas de detección térmica y coordinación de campamentos de salud.", ar:"منصات الطب عن بُعد، إدارة المرضى بالذكاء الاصطناعي، حجز السياحة العلاجية، أنظمة الفحص الحراري، وتنسيق المعسكرات الصحية.", tr:"Tıbbi platformlar, hasta yönetimi yapay zekası, sağlık turizmi rezervasyonu, termal tarama sistemleri ve sağlık kampı koordinasyonu.", fa:"پلتفرم‌های پزشکی از راه دور، هوش مصنوعی مدیریت بیمار، رزرو گردشگری پزشکی، سیستم‌های غربالگری حرارتی و هماهنگی اردوهای بهداشتی." },

svc5_title: { en:"Tourism & Hospitality", fr:"Tourisme & Hôtellerie", es:"Turismo y Hospitalidad", ar:"السياحة والضيافة", tr:"Turizm ve Konaklama", fa:"گردشگری و مهمان‌نوازی" },
svc5_desc: { en:"Multilingual AI tour guides, booking automation, aerial content creation, heritage 3D mapping, and recommendation agents.", fr:"Guides touristiques IA multilingues, automatisation des réservations, création de contenu aérien, cartographie 3D du patrimoine et agents de recommandation.", es:"Guías turísticos IA multilingüe, automatización de reservas, creación de contenido aéreo, mapeo 3D del patrimonio y agentes de recomendación.", ar:"مرادفون سياحيون بالذكاء الاصطناعي متعددو اللغات، أتمتة الحجز، إنشاء محتوى جوي، رسم خرائط ثلاثية الأبعاد للتراث، ووكلاء التوصيات.", tr:"Çok dilli yapay zeka tur rehberleri, rezervasyon otomasyonu, hava içerik oluşturma, miras 3B haritalama ve öneri ajanları.", fa:"راهنمای گردشگری هوش مصنوعی چندزبانه، اتوماسیون رزرو، تولید محتوای هوایی، نقشه‌برداری سه‌بعدی میراث و عامل‌های توصیه." },

svc6_title: { en:"Retail & Restaurant Automation", fr:"Automatisation Commerce & Restaurant", es:"Automatización Comercial y Restaurante", ar:"أتمتة تجارة التجزئة والمطاعم", tr:"Perakende ve Restoran Otomasyonu", fa:"اتوماسیون خرده‌فروشی و رستوران" },
svc6_desc: { en:"WhatsApp/Telegram commerce bots, order management, inventory tracking, multi-location dashboards, and delivery optimization.", fr:"Bots commerciaux WhatsApp/Telegram, gestion des commandes, suivi des stocks, tableaux de bord multi-sites et optimisation des livraisons.", es:"Bots comerciales WhatsApp/Telegram, gestión de pedidos, seguimiento de inventario, paneles multi-sucursal y optimización de entregas.", ar:"روبوتات التجارة عبر واتساب/تيليجرام، إدارة الطلبات، تتبع المخزون، لوحات معلومات متعددة المواقع، وتحسين التوصيل.", tr:"WhatsApp/Telegram ticaret botları, sipariş yönetimi, envanter takibi, çok lokasyonlu panolar ve teslimat optimizasyonu.", fa:"ربات‌های تجاری واتساپ/تلگرام، مدیریت سفارش، ردیابی موجودی، داشبوردهای چندمکانی و بهینه‌سازی تحویل." },

svc7_title: { en:"Industrial & Energy Auditing", fr:"Audit Industriel & Énergétique", es:"Auditoría Industrial y Energética", ar:"التدقيق الصناعي والطاقي", tr:"Endüstriyel ve Enerji Denetimi", fa:"ممیزی صنعتی و انرژی" },
svc7_desc: { en:"Thermal energy audits, electrical hot-spot detection, cold storage monitoring, process optimization, and environmental compliance.", fr:"Audits énergétiques thermiques, détection de points chauds électriques, surveillance du froid industriel, optimisation des processus et conformité environnementale.", es:"Auditorías energéticas térmicas, detección de puntos calientes eléctricos, monitoreo de almacenamiento en frío, optimización de procesos y cumplimiento ambiental.", ar:"تدقيق الطاقة الحرارية، اكتشاف النقاط الساخنة الكهربائية، مراقبة التخزين البارد، تحسين العمليات، والامتثال البيئي.", tr:"Termal enerji denetimleri, elektrik sıcak nokta tespiti, soğuk depo izleme, süreç optimizasyonu ve çevresel uyumluluk.", fa:"ممیزی انرژی حرارتی، شناسایی نقاط داغ الکتریکی، نظارت بر سردخانه، بهینه‌سازی فرآیند و انطباق زیست‌محیطی." },

svc8_title: { en:"App & Agent Development", fr:"Développement d'Apps & Agents", es:"Desarrollo de Apps y Agentes", ar:"تطوير التطبيقات والوكلاء", tr:"Uygulama ve Ajan Geliştirme", fa:"توسعه اپلیکیشن و عامل" },
svc8_desc: { en:"Custom AI agents, white-label automation platforms, government digital services, e-learning systems, and fintech integrations.", fr:"Agents IA personnalisés, plateformes d'automatisation en marque blanche, services numériques gouvernementaux, systèmes e-learning et intégrations fintech.", es:"Agentes IA personalizados, plataformas de automatización de marca blanca, servicios digitales gubernamentales, sistemas de e-learning e integraciones fintech.", ar:"وكلاء ذكاء اصطناعي مخصصون، منصات أتمتة بالعلامة البيضاء، خدمات رقمية حكومية، أنظمة التعلم الإلكتروني، وتكامل التكنولوجيا المالية.", tr:"Özel yapay zeka ajanları, beyaz etiket otomasyon platformları, devlet dijital hizmetleri, e-öğrenme sistemleri ve fintech entegrasyonları.", fa:"عامل‌های هوش مصنوعی سفارشی، پلتفرم‌های اتوماسیون وایت‌لیبل، خدمات دیجیتال دولتی، سیستم‌های یادگیری الکترونیکی و یکپارچه‌سازی فین‌تک." },

svc9_title: { en:"Environmental Monitoring", fr:"Surveillance Environnementale", es:"Monitoreo Ambiental", ar:"المراقبة البيئية", tr:"Çevresel İzleme", fa:"نظارت زیست‌محیطی" },
svc9_desc: { en:"Water quality systems, waste management detection, air quality networks, flood early warning, and carbon offset verification.", fr:"Systèmes de qualité de l'eau, détection de gestion des déchets, réseaux de qualité de l'air, alerte précoce des inondations et vérification des crédits carbone.", es:"Sistemas de calidad del agua, detección de gestión de residuos, redes de calidad del aire, alerta temprana de inundaciones y verificación de compensación de carbono.", ar:"أنظمة جودة المياه، اكتشاف إدارة النفايات، شبكات جودة الهواء، الإنذار المبكر من الفيضانات، والتحقق من تعويضات الكربون.", tr:"Su kalitesi sistemleri, atık yönetimi tespiti, hava kalitesi ağları, sel erken uyarı ve karbon ofset doğrulama.", fa:"سیستم‌های کیفیت آب، شناسایی مدیریت پسماند، شبکه‌های کیفیت هوا، هشدار زودهنگام سیل و تأیید جبران کربن." },

svc10_title: { en:"Data & AI Consulting", fr:"Conseil en Données & IA", es:"Consultoría en Datos e IA", ar:"استشارات البيانات والذكاء الاصطناعي", tr:"Veri ve Yapay Zeka Danışmanlığı", fa:"مشاوره داده و هوش مصنوعی" },
svc10_desc: { en:"AI transformation consulting, geospatial processing, automation audits, training workshops, and market research intelligence.", fr:"Conseil en transformation IA, traitement géospatial, audits d'automatisation, ateliers de formation et intelligence d'études de marché.", es:"Consultoría en transformación IA, procesamiento geoespacial, auditorías de automatización, talleres de capacitación e inteligencia de investigación de mercado.", ar:"استشارات التحول بالذكاء الاصطناعي، المعالجة الجيومكانية، تدقيق الأتمتة، ورش عمل التدريب، وذكاء أبحاث السوق.", tr:"Yapay zeka dönüşüm danışmanlığı, coğrafi veri işleme, otomasyon denetimleri, eğitim atölyeleri ve pazar araştırması istihbaratı.", fa:"مشاوره تحول هوش مصنوعی، پردازش ژئومکانیکی، ممیزی اتوماسیون، کارگاه‌های آموزشی و اطلاعات تحقیقات بازار." },

// ─────────────────────────────────────────────────────────────
// DETAILED SERVICES SECTION
// ─────────────────────────────────────────────────────────────
det_tag: { en:"Deep Dive", fr:"En Profondeur", es:"Análisis Profundo", ar:"تحليل معمّق", tr:"Derinlemesine", fa:"بررسی عمیق" },
det_title: { en:"Solutions That Deliver Results", fr:"Des Solutions Qui Livrent des Résultats", es:"Soluciones Que Entregan Resultados", ar:"حلول تحقق النتائج", tr:"Sonuç Veren Çözümler", fa:"راه‌حل‌هایی که نتیجه می‌دهند" },
det_sub: { en:"Each service module combines our core technologies — AI agents, drone survey, sensor data and autonomous automation.", fr:"Chaque module de service combine nos technologies fondamentales — agents IA, relevés par drone, données de capteurs et automatisation autonome.", es:"Cada módulo de servicio combina nuestras tecnologías principales — agentes IA, levantamiento con drones, datos de sensores y automatización autónoma.", ar:"تجمع كل وحدة خدمية بين تقنياتنا الأساسية — وكلاء الذكاء الاصطناعي، مسح الطائرات بدون طيار، بيانات أجهزة الاستشعار والأتمتة المستقلة.", tr:"Her hizmet modülü temel teknolojilerimizi birleştirir — yapay zeka ajanları, drone taraması, sensör verileri ve otonom otomasyon.", fa:"هر ماژول خدماتی فناوری‌های اصلی ما را ترکیب می‌کند — عامل‌های هوش مصنوعی، نقشه‌برداری پهپادی، داده‌های حسگر و اتوماسیون خودمختار." },

// DETAIL 1: Solar
det1_title: { en:"🔆 Solar Energy Services", fr:"🔆 Services d'Énergie Solaire", es:"🔆 Servicios de Energía Solar", ar:"🔆 خدمات الطاقة الشمسية", tr:"🔆 Güneş Enerjisi Hizmetleri", fa:"🔆 خدمات انرژی خورشیدی" },
det1_desc: { en:"End-to-end solar asset management from initial feasibility through ongoing performance monitoring. Our thermal drone fleet identifies defective cells, micro-cracks, and hot spots that are invisible to the naked eye.", fr:"Gestion complète des actifs solaires de la faisabilité initiale à la surveillance continue des performances. Notre flotte de drones thermiques identifie les cellules défectueuses, les micro-fissures et les points chauds invisibles à l'œil nu.", es:"Gestión integral de activos solares desde la viabilidad inicial hasta el monitoreo continuo de rendimiento. Nuestra flota de drones térmicos identifica celdas defectuosas, microgrietas y puntos calientes invisibles al ojo desnudo.", ar:"إدارة شاملة للأصول الشمسية من الجدوى الأولية حتى المراقبة المستمرة للأداء. أسطولنا من الطائرات بدون طيار الحرارية يحدد الخلايا المعيبة والشقوق الدقيقة والنقاط الساخنة غير المرئية بالعين المجردة.", tr:"İlk fizibiliteden sürekli performans izlemeye kadar uçtan uca güneş varlık yönetimi. Termal drone filomuz, çıplak gözle görülemeyen kusurlu hücreleri, mikro çatlakları ve sıcak noktaları tespit eder.", fa:"مدیریت جامع دارایی‌های خورشیدی از امکان‌سنجی اولیه تا نظارت مستمر بر عملکرد. ناوگان پهپاد حرارتی ما سلول‌های معیوب، میکرترک‌ها و نقاط داغ غیرقابل رؤیت با چشم غیرمسلح را شناسایی می‌کند." },
det1_l1: { en:"Thermal drone panel inspection — per-cell fault detection", fr:"Inspection de panneaux par drone thermique — détection de défauts par cellule", es:"Inspección de paneles con dron térmico — detección de fallas por celda", ar:"فحص الألواح بالطائرات بدون طيار الحرارية — اكتشاف الأعطال لكل خلية", tr:"Termal drone panel denetimi — hücre bazlı arıza tespiti", fa:"بازرسی پنل با پهپاد حرارتی — شناسایی خطا در هر سلول" },
det1_l2: { en:"Automated cleaning service contracts for dusty environments", fr:"Contrats de nettoyage automatisé pour environnements poussiéreux", es:"Contratos de servicio de limpieza automatizada para ambientes polvorientos", ar:"عقود خدمة التنظيف الآلي للبيئات المغبورة", tr:"Tozlu ortamlar için otomatik temizlik hizmet sözleşmeleri", fa:"قرارداد خدمات نظارت خودکار برای محیط‌های پر گرد و غبار" },
det1_l3: { en:"Solar farm feasibility studies with irradiance modelling", fr:"Études de faisabilité de fermes solaires avec modélisation d'irradiance", es:"Estudios de viabilidad de granjas solaires con modelado de irradiancia", ar:"دراسات جدوى المزارع الشمسية مع نمذجة الإشعاع", tr:"Irradiyans modelleme ile güneş çiftliği fizibilite çalışmaları", fa:"مطالعات امکان‌سنجی مزرعه خورشیدی با مدل‌سازی تابش" },
det1_l4: { en:"Real-time performance monitoring dashboard (SaaS)", fr:"Tableau de bord de surveillance des performances en temps réel (SaaS)", es:"Panel de monitoreo de rendimiento en tiempo real (SaaS)", ar:"لوحة معلومات مراقبة الأداء في الوقت الفعلي (SaaS)", tr:"Gerçek zamanlı performans izleme panosu (SaaS)", fa:"داشبورد نظارت بر عملکرد بلادرنگ (SaaS)" },
det1_l5: { en:"Long-term degradation tracking with annual audit reports", fr:"Suivi de dégradation à long terme avec rapports d'audit annuels", es:"Seguimiento de degradación a largo plazo con informes de auditoría anuales", ar:"تتبع التدهور على المدى الطويل مع تدقيق تقارير سنوية", tr:"Yıllık denetim raporlarıyla uzun vadeli bozulma takibi", fa:"ردیابی تخریب بلندمدت با گزارش‌های ممیزی سالانه" },
det1_v_title: { en:"Solar Intelligence", fr:"Intelligence Solaire", es:"Inteligencia Solar", ar:"ذكاء الطاقة الشمسية", tr:"Güneş Zekası", fa:"هوش خورشیدی" },
det1_v_sub: { en:"Thermal resolution: 640×512px | Detection accuracy: 98.5%", fr:"Résolution thermique : 640×512px | Précision de détection : 98,5%", es:"Resolución térmica: 640×512px | Precisión de detección: 98.5%", ar:"الدقة الحرارية: 640×512 بكسل | دقة الاكتشاف: 98.5%", tr:"Termal çözünürlük: 640×512px | Tespit doğruluğu: %98.5", fa:"وضوح حرارتی: 640×512px | دقت شناسایی: 98.5%" },
det1_v_s1: { en:"Faster than manual", fr:"Plus rapide que manuel", es:"Más rápido que manual", ar:"أسرع من اليدوي", tr:"Manuelden daha hızlı", fa:"سریع‌تر از دستی" },
det1_v_s2: { en:"Fault detection rate", fr:"Taux de détection", es:"Tasa de detección", ar:"معدل الاكتشاف", tr:"Tespit oranı", fa:"نرخ شناسایی" },
det1_v_s3: { en:"Cost per panel", fr:"Coût par panneau", es:"Costo por panel", ar:"التكلفة لكل لوح", tr:"Panel başına maliyet", fa:"هزینه هر پنل" },
det1_v_s4: { en:"Report delivery", fr:"Livraison du rapport", es:"Entrega del informe", ar:"تسليم التقرير", tr:"Rapor teslimi", fa:"تحویل گزارش" }
};