/* ═══════════════════════════════════════════════════════════════
   EDGE Global Solutions — 6-Language Translation Dictionary
   Languages: EN, FR, ES, AR, TR, FA
   Part 2: Detailed Services, Markets, Why Us, Contact, Footer
   ═══════════════════════════════════════════════════════════════ */

const translations_p2 = {

// DETAIL 1 Solar continued
det1_v_s1: { en:"Faster than manual", fr:"Plus rapide que manuel", es:"Más rápido que manual", ar:"أسرع من اليدوي", tr:"Manuelden daha hızlı", fa:"سریع‌تر از دستی" },
det1_v_s2: { en:"Fault detection rate", fr:"Taux de détection", es:"Tasa de detección", ar:"معدل الاكتشاف", tr:"Tespit oranı", fa:"نرخ شناسایی" },
det1_v_s3: { en:"Cost per panel", fr:"Coût par panneau", es:"Costo por panel", ar:"التكلفة لكل لوح", tr:"Panel başına maliyet", fa:"هزینه هر پنل" },
det1_v_s4: { en:"Report delivery", fr:"Livraison du rapport", es:"Entrega del informe", ar:"تسليم التقرير", tr:"Rapor teslimi", fa:"تحویل گزارش" },

// DETAIL 2: Agriculture
det2_title: { en:"🌾 Precision Agriculture", fr:"🌾 Agriculture de Précision", es:"🌾 Agricultura de Precisión", ar:"🌾 الزراعة الدقيقة", tr:"🌾 Hassas Tarım", fa:"🌾 کشاورزی دقیق" },
det2_desc: { en:"Data-driven farming solutions that increase yields while reducing water and chemical inputs. Our multispectral drones map crop stress weeks before it becomes visible.", fr:"Solutions agricoles basées sur les données qui augmentent les rendements tout en réduisant les intrants en eau et en produits chimiques.", es:"Soluciones agrícolas basadas en datos que aumentan los rendimientos mientras reducen el agua y los insumos químicos.", ar:"حلول زراعية مبنية على البيانات تزيد الإنتاجية مع تقليل المياه والمدخلات الكيميائية.", tr:"Veri odaklı tarım çözümleri—su ve kimyasal girdileri azaltırken verimi artırır.", fa:"راه‌حل‌های کشاورزی مبتنی بر داده که عملکرد را افزایش و مصرف آب و مواد شیمیایی را کاهش می‌دهند." },
det2_l1: { en:"NDVI and multispectral crop health monitoring", fr:"Surveillance NDVI et multispectrale des cultures", es:"Monitoreo NDVI y multiespectral de cultivos", ar:"مراقبة صحة المحاصيل NDVI ومتعددة الأطياف", tr:"NDVI ve multispektral ürün sağlığı izleme", fa:"نظارت NDVI و چندطیفی سلامت محصول" },
det2_l2: { en:"Irrigation zone optimization using thermal soil moisture maps", fr:"Optimisation des zones d'irrigation par cartes thermiques d'humidité du sol", es:"Optimización de zonas de riego con mapas térmicos de humedad del suelo", ar:"تحسين مناطق الري باستخدام خرائط رطوبة التربة الحرارية", tr:"Termal toprak nemi haritalarıyla sulama bölgesi optimizasyonu", fa:"بهینه‌سازی منطقه آبیاری با نقشه‌های حرارتی رطوبت خاک" },
det2_l3: { en:"Early pest and disease detection via spectral signatures", fr:"Détection précoce des parasites et maladies par signatures spectrales", es:"Detección temprana de plagas y enfermedades mediante firmas espectrales", ar:"الكشف المبكر عن الآفات والأمراض عبر التوقيعات الطيفية", tr:"Spektral imzalarla erken zararlı ve hastalık tespiti", fa:"شناسایی زودهنگام آفات و بیماری‌ها از طریق امضاهای طیفی" },
det2_l4: { en:"Livestock heat stress monitoring with automated alerts", fr:"Surveillance du stress thermique du bétail avec alertes automatiques", es:"Monitoreo de estrés por calor en ganado con alertas automatizadas", ar:"مراقبة الإجهاد الحراري للماشية مع تنبيهات آلية", tr:"Otomatik uyarılarla hayvan sıcak stresi izleme", fa:"نظارت استرس گرمایی دام با هشدارهای خودکار" },
det2_l5: { en:"Seasonal yield prediction and harvest planning AI", fr:"IA de prédiction de rendement saisonnier et planification de récolte", es:"IA de predicción de rendimiento estacional y planificación de cosecha", ar:"ذكاء اصطناعي للتنبؤ بالموسمية وخطط الحصاد", tr:"Mevsimsel verim tahmini ve hasat planlama yapay zekası", fa:"پیش‌بینی عملکرد فصلی و هوش مصنوعی برنامه‌ریزی برداشت" },
det2_v_title: { en:"Smart Farming", fr:"Agriculture Intelligente", es:"Agricultura Inteligente", ar:"الزراعة الذكية", tr:"Akıllı Tarım", fa:"کشاورزی هوشمند" },
det2_v_sub: { en:"Precision agriculture powered by aerial intelligence", fr:"Agriculture de précision alimentée par l'intelligence aérienne", es:"Agricultura de precisión impulsada por inteligencia aérea", ar:"الزراعة الدقيقة المدعومة بالذكاء الجوي", tr:"Hava istihbaratıyla desteklenen hassas tarım", fa:"کشاورزی دقیق مبتنی بر هوش هوایی" },
det2_v_s1: { en:"Water savings", fr:"Économie d'eau", es:"Ahorro de agua", ar:"توفير المياه", tr:"Su tasarrufu", fa:"صرفه‌جویی آب" },
det2_v_s2: { en:"Yield increase", fr:"Augmentation du rendement", es:"Aumento de rendimiento", ar:"زيادة الإنتاجية", tr:"Verim artışı", fa:"افزایش عملکرد" },
det2_v_s3: { en:"Less pesticide", fr:"Moins de pesticides", es:"Menos pesticida", ar:"مبيدات أقل", tr:"Daha az pestisit", fa:"کمتر سموم" },
det2_v_s4: { en:"Early detection", fr:"Détection précoce", es:"Detección temprana", ar:"الكشف المبكر", tr:"Erken tespit", fa:"شناسایی زودهنگام" },

// DETAIL 3: Automation
det3_title: { en:"🏪 Business Automation", fr:"🏪 Automatisation Commerciale", es:"🏪 Automatización de Negocios", ar:"🏪 أتمتة الأعمال", tr:"🏪 İş Otomasyonu", fa:"🏪 اتوماسیون کسب‌وکار" },
det3_desc: { en:"AI-powered automation for restaurants, shops, and service businesses. Our autonomous agents handle orders, reservations, inventory, customer communication and delivery coordination — 24/7.", fr:"Automatisation alimentée par l'IA pour restaurants, commerces et entreprises de services. Nos agents autonomes gèrent les commandes, réservations, inventaires, communication client et coordination des livraisons — 24h/24.", es:"Automatización con IA para restaurantes, tiendas y negocios de servicios. Nuestros agentes autónomos gestionan pedidos, reservas, inventario, comunicación con clientes y coordinación de entregas — 24/7.", ar:"أتمتة مدعومة بالذكاء الاصطناعي للمطاعم والمتاجر وشركات الخدمات. وكلاؤنا المستقلون يتعاملون مع الطلبات والحجوزات والمخزون وخدمة العملاء والتنسيق — على مدار الساعة.", tr:"Restoranlar, mağazalar ve hizmet işletmeleri için yapay zeka destekli otomasyon. Otonom ajanlarımız siparişleri, rezervasyonları, envanteri, müşteri iletişimini ve teslimat koordinasyonunu 7/24 yönetir.", fa:"اتوماسیون مبتنی بر هوش مصنوعی برای رستوران‌ها، مغازه‌ها و کسب‌وکارهای خدماتی. عامل‌های خودمختار ما سفارشات، رزروها، موجودی، ارتباط با مشتری و هماهنگی تحویل را ۲۴/۷ مدیریت می‌کنند." },
det3_l1: { en:"WhatsApp & Telegram ordering and reservation bots", fr:"Bots de commande et réservation WhatsApp & Telegram", es:"Bots de pedidos y reservas WhatsApp y Telegram", ar:"روبوتات الطلبات والحجوزات عبر واتساب وتيليجرام", tr:"WhatsApp ve Telegram sipariş ve rezervasyon botları", fa:"ربات‌های سفارش و رزرو واتساپ و تلگرام" },
det3_l2: { en:"Automated inventory management with predictive reorder", fr:"Gestion d'inventaire automatisée avec réapprovisionnement prédictif", es:"Gestión de inventario automatizada con reabastecimiento predictivo", ar:"إدارة المخزون الآلية مع إعادة الطلب التنبؤية", tr:"Tahmini yeniden sipariş ile otomatik envanter yönetimi", fa:"مدیریت موجودی خودکار با سفارش مجدد پیش‌بینانه" },
det3_l3: { en:"Multi-location analytics dashboard with real-time KPIs", fr:"Tableau de bord analytique multi-sites avec KPI en temps réel", es:"Panel de análisis multi-sucursal con KPIs en tiempo real", ar:"لوحة تحليلات متعددة المواقع مع مؤشرات أداء في الوقت الفعلي", tr:"Gerçek zamanlı KPI'larla çok lokasyonlu analitik panosu", fa:"داشبورد تحلیلی چندمکانی با KPI بلادرنگ" },
det3_l4: { en:"Delivery route optimization and fleet coordination", fr:"Optimisation des itinéraires de livraison et coordination de flotte", es:"Optimización de rutas de entrega y coordinación de flota", ar:"تحسين مسارات التوصيل وتنسيق الأسطول", tr:"Teslimat güzergahı optimizasyonu ve filo koordinasyonu", fa:"بهینه‌سازی مسیر تحویل و هماهنگی ناوگان" },
det3_l5: { en:"Multilingual customer support AI agents", fr:"Agents IA de support client multilingue", es:"Agentes IA de soporte al cliente multilingüe", ar:"وكلاء دعم العملاء بالذكاء الاصطناعي متعددو اللغات", tr:"Çok dilli müşteri destek yapay zeka ajanları", fa:"عامل‌های هوش مصنوعی پشتیبانی مشتری چندزبانه" },
det3_v_title: { en:"Autonomous Operations", fr:"Opérations Autonomes", es:"Operaciones Autónomas", ar:"العمليات المستقلة", tr:"Otonom Operasyonlar", fa:"عملیات خودمختار" },
det3_v_sub: { en:"AI agents that work while you sleep", fr:"Des agents IA qui travaillent pendant que vous dormez", es:"Agentes IA que trabajan mientras duermes", ar:"وكلاء ذكاء اصطناعي يعملون أثناء نومك", tr:"Siz uyurken çalışan yapay zeka ajanları", fa:"عامل‌های هوش مصنوعی که وقتی می‌خوابید کار می‌کنند" },
det3_v_s1: { en:"Always on", fr:"Toujours actif", es:"Siempre activo", ar:"يعمل دائماً", tr:"Her zaman açık", fa:"همیشه فعال" },
det3_v_s2: { en:"Languages", fr:"Langues", es:"Idiomas", ar:"لغات", tr:"Dil", fa:"زبان‌ها" },
det3_v_s3: { en:"Task automation", fr:"Automatisation des tâches", es:"Automatización de tareas", ar:"أتمتة المهام", tr:"Görev otomasyonu", fa:"اتوماسیون وظایف" },
det3_v_s4: { en:"Response time", fr:"Temps de réponse", es:"Tiempo de respuesta", ar:"وقت الاستجابة", tr:"Yanıt süresi", fa:"زمان پاسخ" },

// DETAIL 4: Healthcare
det4_title: { en:"🏥 Healthcare Technology", fr:"🏥 Technologie de Santé", es:"🏥 Tecnología de Salud", ar:"🏥 تقنية الرعاية الصحية", tr:"🏥 Sağlık Teknolojisi", fa:"🏥 فناوری بهداشت و درمان" },
det4_desc: { en:"Digital health platforms bridging patients and providers. From telemedicine in rural Africa to medical tourism coordination in Turkey — technology that saves lives and generates revenue.", fr:"Plateformes de santé numériques reliant patients et prestataires. De la télémédecine en Afrique rurale à la coordination du tourisme médical en Turquie.", es:"Plataformas de salud digital que conectan pacientes y proveedores. Desde telemedicina en el África rural hasta coordinación de turismo médico en Turquía.", ar:"منصات صحية رقمية تربط بين المرضى ومقدمي الرعاية. من الطب عن بُعد في أفريقيا الريفية إلى تنسيق السياحة العلاجية في تركيا.", tr:"Hastaları ve sağlayıcıları birleştiren dijital sağlık platformları. Kırsal Afrika'da telemedicine'den Türkiye'de sağlık turizmi koordinasyonuna.", fa:"پلتفرم‌های سلامت دیجیتال که بیماران و ارائه‌دهندگان را به هم متصل می‌کنند." },
det4_l1: { en:"White-label telemedicine platform for clinics and hospitals", fr:"Plateforme de télémédecine en marque blanche pour cliniques et hôpitaux", es:"Plataforma de telemedicina de marca blanca para clínicas y hospitales", ar:"منصة طب عن بُعد بالعلامة البيضاء للعيادات والمستشفيات", tr:"Klinikler ve hastaneler için beyaz etiket telemedicine platformu", fa:"پلتفرم پزشکی از راه دور وایت‌لیبل برای کلینیک‌ها و بیمارستان‌ها" },
det4_l2: { en:"Medical tourism booking engine (Turkey, Iran, ME)", fr:"Moteur de réservation de tourisme médical (Turquie, Iran, MO)", es:"Motor de reservas de turismo médico (Turquía, Iran, ME)", ar:"محرك حجز السياحة العلاجية (تركيا، إيران، الشرق الأوسط)", tr:"Sağlık turizmi rezervasyon motoru (Türkiye, İran, MO)", fa:"موتور رزرو گردشگری پزشکی (ترکیه، ایران، خاورمیانه)" },
det4_l3: { en:"AI appointment scheduling and patient follow-up agents", fr:"Agents IA de prise de rendez-vous et suivi des patients", es:"Agentes IA de programación de citas y seguimiento de pacientes", ar:"وكلاء جدولة المواعيد ومتابعة المرضى بالذكاء الاصطناعي", tr:"Yapay zeka randevu planlama ve hasta takip ajanları", fa:"عامل‌های هوش مصنوعی زمان‌بندی قرار ملاقات و پیگیری بیمار" },
det4_l4: { en:"Thermal screening stations for airports and hospitals", fr:"Stations de dépistage thermique pour aéroports et hôpitaux", es:"Estaciones de detección térmica para aeropuertos y hospitales", ar:"محطات الفحص الحراري للمطارات والمستشفيات", tr:"Havalimanları ve hastaneler için termal tarama istasyonları", fa:"ایستگاه‌های غربالگری حرارتی برای فرودگاه‌ها و بیمارستان‌ها" },
det4_l5: { en:"Health camp coordination platform for NGOs and governments", fr:"Plateforme de coordination de camps de santé pour ONG et gouvernements", es:"Plataforma de coordinación de campamentos de salud para ONGs y gobiernos", ar:"منصة تنسيق المعسكرات الصحية للمنظمات غير الحكومية والحكومات", tr:"STK'lar ve hükümetler için sağlık kampı koordinasyon platformu", fa:"پلتفرم هماهنگی اردوهای بهداشتی برای NGOها و دولت‌ها" },
det4_v_title: { en:"Digital Health", fr:"Santé Numérique", es:"Salud Digital", ar:"الصحة الرقمية", tr:"Dijital Sağlık", fa:"سلامت دیجیتال" },
det4_v_sub: { en:"Connecting patients to care across borders", fr:"Connecter les patients aux soins au-delà des frontières", es:"Conectando pacientes con atención a través de fronteras", ar:"ربط المرضى بالرعاية عبر الحدود", tr:"Hastaları sınırlar ötesinde bakım ile buluşturmak", fa:"اتصال بیماران به خدمات درمانی فرامرزی" },
det4_v_s1: { en:"Turkey med tourism", fr:"Tourisme médical Turquie", es:"Turismo médico Turquía", ar:"السياحة العلاجية تركيا", tr:"TR sağlık turizmi", fa:"گردشگری پزشکی ترکیه" },
det4_v_s2: { en:"Faster booking", fr:"Réservation plus rapide", es:"Reserva más rápida", ar:"حجز أسرع", tr:"Daha hızlı rezervasyon", fa:"رزرو سریع‌تر" },
det4_v_s3: { en:"Languages", fr:"Langues", es:"Idiomas", ar:"لغات", tr:"Dil", fa:"زبان‌ها" },
det4_v_s4: { en:"Uptime SLA", fr:"SLA de disponibilité", es:"SLA de disponibilidad", ar:"اتفاقية مستوى الخدمة", tr:"Uptime SLA", fa:"SLA زمان فعال" },

// ─────────────────────────────────────────────────────────────
// MARKETS SECTION
// ─────────────────────────────────────────────────────────────
mkt_tag: { en:"Global Reach", fr:"Portée Mondiale", es:"Alcance Global", ar:"الوصول العالمي", tr:"Küresel Erişim", fa:"دسترسی جهانی" },
mkt_title: { en:"Serving Six Continental Regions", fr:"Au Service de Six Régions Continentales", es:"Sirviendo a Seis Regiones Continentales", ar:"نخدم ست مناطق قارية", tr:"Altı Kıtasal Bölgeye Hizmet", fa:"خدمت به شش منطقه قاره‌ای" },
mkt_sub: { en:"Local expertise, global technology. We operate where opportunity meets innovation.", fr:"Expertise locale, technologie mondiale. Nous opérons là où l'opportunité rencontre l'innovation.", es:"Experiencia local, tecnología global. Operamos donde la oportunidad se encuentra con la innovación.", ar:"خبرة محلية، تقنية عالمية. نعمل حيث تلتقي الفرص بالابتكار.", tr:"Yerel uzmanlık, küresel teknoloji. Fırsatın inovasyonla buluştuğu yerde çalışıyoruz.", fa:"تخصص محلی، فناوری جهانی. ما جایی فعالیت می‌کنیم که فرصت با نوآوری ملاقات می‌کند." },
mkt1_name: { en:"European Union", fr:"Union Européenne", es:"Unión Europea", ar:"الاتحاد الأوروبي", tr:"Avrupa Birliği", fa:"اتحادیه اروپا" },
mkt1_desc: { en:"Energy efficiency mandates, aging infrastructure inspection, precision viticulture, and strict environmental compliance.", fr:"Mandats d'efficacité énergétique, inspection d'infrastructures vieillissantes, viticulture de précision et conformité environnementale stricte.", es:"Mandatos de eficiencia energética, inspección de infraestructura envejecida, viticultura de precisión y cumplimiento ambiental estricto.", ar:"تفويضات كفاءة الطاقة، فحص البنية التحتية القديمة، كرمة دقيقة، وامتثال بيئي صارم.", tr:"Enerji verimliliği zorunlulukları, yaşlanan altyapı denetimi, hassas bağcılık ve sıkı çevresel uyumluluk.", fa:"تکالیف بهره‌وری انرژی، بازرسی زیرساخت‌های فرسوده، تاک‌داری دقیق و انطباق زیست‌محیطی سختگیرانه." },
mkt1_t1: { en:"Energy Audits", fr:"Audits Énergétiques", es:"Auditorías Energéticas", ar:"تدقيق الطاقة", tr:"Enerji Denetimleri", fa:"ممیزی انرژی" },
mkt1_t2: { en:"Solar", fr:"Solaire", es:"Solar", ar:"شمسي", tr:"Güneş", fa:"خورشیدی" },
mkt1_t3: { en:"Compliance", fr:"Conformité", es:"Cumplimiento", ar:"امتثال", tr:"Uyumluluk", fa:"انطباق" },
mkt1_t4: { en:"Carbon Markets", fr:"Marchés Carbone", es:"Mercados de Carbono", ar:"أسواق الكربون", tr:"Karbon Pazarları", fa:"بازارهای کربن" },

mkt2_name: { en:"South America", fr:"Amérique du Sud", es:"Sudamérica", ar:"أمريكا الجنوبية", tr:"Güney Amerika", fa:"آمریکای جنوبی" },
mkt2_desc: { en:"Large-scale commercial agriculture, urban restaurant tech, delivery ecosystem integration, and environmental monitoring.", fr:"Agriculture commerciale à grande échelle, technologie de restauration urbaine, intégration de l'écosystème de livraison et surveillance environnementale.", es:"Agricultura comercial a gran escala, tecnología de restaurantes urbanos, integración del ecosistema de entrega y monitoreo ambiental.", ar:"زراعة تجارية واسعة النطاق، تقنية المطاعم الحضرية، تكامل نظام التوصيل، والمراقبة البيئية.", tr:"Büyük ölçekli ticari tarım, kentsel restoran teknolojisi, teslimat ekosistemi entegrasyonu ve çevresel izleme.", fa:"کشاورزی تجاری در مقیاس بزرگ، فناوری رستوران شهری، یکپارچه‌سازی اکوسیستم تحویل و نظارت زیست‌محیطی." },
mkt2_t1: { en:"Agribusiness", fr:"Agroalimentaire", es:"Agroindustria", ar:"الأعمال الزراعية", tr:"Tarım İşletmeciliği", fa:"کشاورزی تجاری" },
mkt2_t2: { en:"Restaurant Tech", fr:"Tech Restaurant", es:"Tecnología Restaurantera", ar:"تقنية المطاعم", tr:"Restoran Teknolojisi", fa:"فناوری رستوران" },
mkt2_t3: { en:"Logistics", fr:"Logistique", es:"Logística", ar:"اللوجستيات", tr:"Lojistik", fa:"لجستیک" },
mkt2_t4: { en:"Fintech", fr:"Fintech", es:"Fintech", ar:"التكنولوجيا المالية", tr:"Fintech", fa:"فین‌تک" },

mkt3_name: { en:"Africa", fr:"Afrique", es:"África", ar:"أفريقيا", tr:"Afrika", fa:"آفریقا" },
mkt3_desc: { en:"Leapfrog mobile-first markets, WhatsApp commerce, precision agriculture for smallholders, telemedicine, and capacity building.", fr:"Marchés mobile-first, commerce WhatsApp, agriculture de précision pour petits exploitants, télémédecine et renforcement des capacités.", es:"Mercados móviles de salto tecnológico, comercio WhatsApp, agricultura de precisión para pequeños agricultores, telemedicina y desarrollo de capacidades.", ar:"أسواق الجوال المتقدمة، التجارة عبر واتساب، الزراعة الدقيقة للمزارعين الصغار، الطب عن بُعد، وبناء القدرات.", tr:"Mobil-ilk atlama pazarları, WhatsApp ticareti, küçük çiftçiler için hassas tarım, telemedicine ve kapasite geliştirme.", fa:"بازارهای موبایل‌اول، تجارت واتساپ، کشاورزی دقیق برای خرده‌مالکان، پزشکی از راه دور و توانمندسازی." },
mkt3_t1: { en:"WhatsApp Bots", fr:"Bots WhatsApp", es:"Bots WhatsApp", ar:"روبوتات واتساب", tr:"WhatsApp Botları", fa:"ربات‌های واتساپ" },
mkt3_t2: { en:"Telemedicine", fr:"Télémédecine", es:"Telemedicina", ar:"الطب عن بُعد", tr:"Telemedicine", fa:"پزشکی از راه دور" },
mkt3_t3: { en:"Agriculture", fr:"Agriculture", es:"Agricultura", ar:"الزراعة", tr:"Tarım", fa:"کشاورزی" },
mkt3_t4: { en:"Training", fr:"Formation", es:"Capacitación", ar:"التدريب", tr:"Eğitim", fa:"آموزش" },

mkt4_name: { en:"Turkey", fr:"Turquie", es:"Turquía", ar:"تركيا", tr:"Türkiye", fa:"ترکیه" },
mkt4_desc: { en:"Medical tourism hub, post-earthquake infrastructure inspection, manufacturing automation, and booming restaurant sector.", fr:"Hub de tourisme médical, inspection d'infrastructure post-sismique, automatisation manufacturière et secteur de la restauration en plein essor.", es:"Centro de turismo médico, inspección de infraestructura post-terremoto, automatización manufacturera y sector restaurantero en auge.", ar:"مركز السياحة العلاجية، فحص البنية التحتية بعد الزلزال، أتمتة التصنيع، وقطاع المطاعم المزدهر.", tr:"Sağlık turizmi merkezi, deprem sonrası altyapı denetimi, üretim otomasyonu ve hızla büyüyen restoran sektörü.", fa:"قطب گردشگری پزشکی، بازرسی زیرساخت پس از زلزله، اتوماسیون تولید و بخش رستوران رو به رشد." },
mkt4_t1: { en:"Medical Tourism", fr:"Tourisme Médical", es:"Turismo Médico", ar:"السياحة العلاجية", tr:"Sağlık Turizmi", fa:"گردشگری پزشکی" },
mkt4_t2: { en:"Construction", fr:"Construction", es:"Construcción", ar:"البناء", tr:"İnşaat", fa:"ساخت‌وساز" },
mkt4_t3: { en:"Manufacturing", fr:"Manufacture", es:"Manufactura", ar:"التصنيع", tr:"Üretim", fa:"تولید" },
mkt4_t4: { en:"Hospitality", fr:"Hôtellerie", es:"Hospitalidad", ar:"الضيافة", tr:"Konaklama", fa:"مهمان‌نوازی" },

mkt5_name: { en:"Iran", fr:"Iran", es:"Irán", ar:"إيران", tr:"İran", fa:"ایران" },
mkt5_desc: { en:"Critical water scarcity solutions, untapped heritage tourism, agricultural optimization, and telemedicine for rural communities.", fr:"Solutions critiques de pénurie d'eau, tourisme patrimonial inexploité, optimisation agricole et télémédecine pour les communautés rurales.", es:"Soluciones críticas de escasez de agua, turismo patrimonial desaprovechado, optimización agrícola y telemedicina para comunidades rurales.", ar:"حلول ندرة المياه الحرجة، السياحة التراثية غير المستغلة، التحسين الزراعي، والطب عن بُعد للمجتمعات الريفية.", tr:"Kritik su kıtlığı çözümleri, değerlendirilmemiş miras turizmi, tarım optimizasyonu ve kırsal topluluklar için telemedicine.", fa:"راه‌حل‌های بحران کم‌آبی، گردشگری میراث بهره‌برداری‌نشده، بهینه‌سازی کشاورزی و پزشکی از راه دور برای جوامع روستایی." },
mkt5_t1: { en:"Water Monitoring", fr:"Surveillance de l'Eau", es:"Monitoreo del Agua", ar:"مراقبة المياه", tr:"Su İzleme", fa:"نظارت آب" },
mkt5_t2: { en:"Heritage Tourism", fr:"Tourisme Patrimonial", es:"Turismo del Patrimonio", ar:"السياحة التراثية", tr:"Miras Turizmi", fa:"گردشگری میراث" },
mkt5_t3: { en:"Agriculture", fr:"Agriculture", es:"Agricultura", ar:"الزراعة", tr:"Tarım", fa:"کشاورزی" },
mkt5_t4: { en:"Healthcare", fr:"Santé", es:"Salud", ar:"الرعاية الصحية", tr:"Sağlık", fa:"بهداشت و درمان" },

mkt6_name: { en:"Middle East & Arab States", fr:"Moyen-Orient & États Arabes", es:"Medio Oriente y Estados Árabes", ar:"الشرق الأوسط والدول العربية", tr:"Ortadoğu ve Arap Devletleri", fa:"خاورمیانه و کشورهای عربی" },
mkt6_desc: { en:"Mega-project monitoring, solar farm maintenance in harsh climates, luxury tourism experiences, and Vision 2030 digital transformation.", fr:"Surveillance de méga-projets, maintenance de fermes solaires en climats difficiles, expériences touristiques de luxe et transformation numérique Vision 2030.", es:"Monitoreo de megaproyectos, mantenimiento de granjas solares en climas extremos, experiencias turísticas de lujo y transformación digital Visión 2030.", ar:"مراقبة المشاريع الضخمة، صيانة المزارع الشمسية في المناخات القاسية، تجارب سياحية فاخرة، والتحول الرقمي رؤية 2030.", tr:"Mega proje izleme, zorlu iklimlerde güneş çiftliği bakımı, lüks turizm deneyimleri ve Vizyon 2030 dijital dönüşümü.", fa:"نظارت مگاپروژه‌ها، نگهداری مزرعه خورشیدی در اقلیم‌های سخت، تجربه‌های گردشگری لوکس و تحول دیجیتال چشم‌انداز 2030." },
mkt6_t1: { en:"Solar Cleaning", fr:"Nettoyage Solaire", es:"Limpieza Solar", ar:"تنظيف الألواح الشمسية", tr:"Güneş Temizliği", fa:"نظافت خورشیدی" },
mkt6_t2: { en:"Mega Projects", fr:"Méga Projets", es:"Mega Proyectos", ar:"مشاريع ضخمة", tr:"Mega Projeler", fa:"مگاپروژه‌ها" },
mkt6_t3: { en:"Water", fr:"Eau", es:"Agua", ar:"المياه", tr:"Su", fa:"آب" },
mkt6_t4: { en:"Smart Cities", fr:"Villes Intelligentes", es:"Ciudades Inteligentes", ar:"المدن الذكية", tr:"Akıllı Şehirler", fa:"شهرهای هوشمند" },

// ─────────────────────────────────────────────────────────────
// WHY US
// ─────────────────────────────────────────────────────────────
why_tag: { en:"Our Edge", fr:"Notre Avantage", es:"Nuestra Ventaja", ar:"ميّزتنا", tr:"Avantajımız", fa:"برتری ما" },
why_title: { en:"Why Choose EDGE Global", fr:"Pourquoi Choisir EDGE Global", es:"Por Qué Elegir EDGE Global", ar:"لماذا تختار EDGE Global", tr:"Neden EDGE Global", fa:"چرا EDGE Global را انتخاب کنید" },
why_sub: { en:"A rare combination of AI, hardware, and domain expertise — under one roof.", fr:"Une combinaison rare d'IA, de matériel et d'expertise métier — sous un même toit.", es:"Una combinación rara de IA, hardware y experiencia en el dominio — todo bajo un mismo techo.", ar:"نادرة من الذكاء الاصطناعي والأجهزة والخبرة المجالية — تحت سقف واحد.", tr:"Yapay zeka, donanım ve alan uzmanlığının nadir birleşimi — tek çatı altında.", fa:"ترکیبی نادر از هوش مصنوعی، سخت‌افزار و تخصص حوزه‌ای — زیر یک سقف." },
why1_title: { en:"Autonomous AI Agents", fr:"Agents IA Autonomes", es:"Agentes IA Autónomos", ar:"وكلاء ذكاء اصطناعي مستقلون", tr:"Otonom Yapay Zeka Ajanları", fa:"عامل‌های خودمختار هوش مصنوعی" },
why1_desc: { en:"Self-operating agents that schedule jobs, process data, generate reports and deliver results — no human intervention needed.", fr:"Agents autonomes qui planifient les tâches, traitent les données, génèrent des rapports et livrent les résultats — sans intervention humaine.", es:"Agentes autónomos que programan trabajos, procesan datos, generan informes y entregan resultados — sin intervención humana.", ar:"وكلاء ذاتيون يجدولون المهام ويعالجون البيانات وينتجون التقارير ويقدمون النتائج — دون تدخل بشري.", tr:"İşleri zamanlayan, verileri işleyen, raporlar oluşturan ve sonuçlar sunan otonom ajanlar — insan müdahalesi gerektirmez.", fa:"عامل‌های خودکار که کارها را زمان‌بندی، داده‌ها را پردازش، گزارش‌ها تولید و نتایج ارائه می‌دهند — بدون نیاز به دخالت انسانی." },
why2_title: { en:"Drone + Sensor Fleet", fr:"Flotte de Drones + Capteurs", es:"Flota de Drones + Sensores", ar:"أسطول الطائرات بدون طيار وأجهزة الاستشعار", tr:"Drone + Sensör Filosu", fa:"ناوگان پهپاد + حسگر" },
why2_desc: { en:"Professional-grade thermal, multispectral and gamma-ray sensors mounted on survey-grade drones for precision data acquisition.", fr:"Capteurs thermiques, multispectraux et gamma professionnels montés sur des drones de relevé pour l'acquisition de données de précision.", es:"Sensores térmicos, multiespectrales y de rayos gamma de grado profesional montados en drones de levantamiento.", ar:"أجهزة استشعار حرارية ومتعددة الأطياف وأشعة غاما احترافية مثبتة على طائرات مسح بدقة عالية.", tr:"Profesyonel termal, multispektral ve gama ışını sensörleri, hassas veri toplama için araştırma sınıfı drone'lara monte edilmiş.", fa:"حسگرهای حرارتی، چندطیفی و پرتو گامای حرفه‌ای نصب‌شده روی پهپادهای نقشه‌برداری برای جمع‌آوری داده دقیق." },
why3_title: { en:"6-Language Capability", fr:"Capacité 6 Langues", es:"Capacidad en 6 Idiomas", ar:"قدرة ست لغات", tr:"6 Dil Yeteneği", fa:"قابلیت ۶ زبانه" },
why3_desc: { en:"Full native support in English, French, Spanish, Arabic, Turkish and Farsi — covering all target markets natively.", fr:"Support natif complet en anglais, français, espagnol, arabe, turc et persan — couvrant tous les marchés cibles.", es:"Soporte nativo completo en inglés, francés, español, árabe, turco y persa — cubriendo todos los mercados objetivo.", ar:"دعم أصلي كامل بالإنجليزية والفرنسية والإسبانية والعربية والتركية والفارسية — يغطي جميع الأسواق المستهدفة.", tr:"İngilizce, Fransızca, İspanyolca, Arapça, Türkçe ve Farsça tam yerel destek — tüm hedef pazarları kapsar.", fa:"پشتیبانی بومی کامل به انگلیسی، فرانسوی، اسپانیایی، عربی، ترکی و فارسی — پوشش تمام بازارهای هدف." },
why4_title: { en:"Rapid Deployment", fr:"Déploiement Rapide", es:"Despliegue Rápido", ar:"نشر سريع", tr:"Hızlı Dağıtım", fa:"استقرار سریع" },
why4_desc: { en:"Modular architecture means we deploy new solutions in days, not months. Same engine, different configurations per market.", fr:"L'architecture modulaire nous permet de déployer de nouvelles solutions en jours, pas en mois. Même moteur, configurations différentes par marché.", es:"La arquitectura modular significa que implementamos nuevas soluciones en días, no meses. Mismo motor, configuraciones diferentes por mercado.", ar:"البنية المعيارية تعني أننا ننشر حلولاً جديدة في أيام وليس أشهر. نفس المحرك، تكوينات مختلفة لكل سوق.", tr:"Modüler mimari, yeni çözümleri aylar değil günler içinde dağıtmamızı sağlar. Aynı motor, pazara göre farklı yapılandırmalar.", fa:"معماری ماژولار به این معنی است که راه‌حل‌های جدید را در روزها نه ماه‌ها مستقر می‌کنیم. موتور یکسان، پیکربندی‌های متفاوت برای هر بازار." },
why5_title: { en:"Automated Reporting", fr:"Rapports Automatisés", es:"Informes Automatizados", ar:"تقارير آلية", tr:"Otomatik Raporlama", fa:"گزارش‌دهی خودکار" },
why5_desc: { en:"Every service includes intelligent report generation — PDF, HTML, CSV — delivered via email, Telegram, or cloud storage.", fr:"Chaque service inclut la génération intelligente de rapports — PDF, HTML, CSV — livrés par email, Telegram ou stockage cloud.", es:"Cada servicio incluye generación inteligente de informes — PDF, HTML, CSV — entregados por email, Telegram o almacenamiento en la nube.", ar:"كل خدمة تشمل إنشاء تقارير ذكية — PDF، HTML، CSV — تُسلّم عبر البريد الإلكتروني أو تيليجرام أو التخزين السحابي.", tr:"Her hizmet, akıllı rapor oluşturmayı içerir — PDF, HTML, CSV — e-posta, Telegram veya bulut depolama ile teslim edilir.", fa:"هر خدمات شامل تولید هوشمند گزارش — PDF، HTML، CSV — از طریق ایمیل، تلگرام یا فضای ابری تحویل داده می‌شود." },
why6_title: { en:"Enterprise Security", fr:"Sécurité Entreprise", es:"Seguridad Empresarial", ar:"أمان المؤسسات", tr:"Kurumsal Güvenlik", fa:"امنیت سازمانی" },
why6_desc: { en:"OAuth 2.0, encrypted data pipelines, GDPR-compliant processing, and secure cloud infrastructure across all regions.", fr:"OAuth 2.0, pipelines de données chiffrés, traitement conforme au RGPD et infrastructure cloud sécurisée dans toutes les régions.", es:"OAuth 2.0, tuberías de datos encriptados, procesamiento conforme al RGPD e infraestructura cloud segura en todas las regiones.", ar:"OAuth 2.0، خطوط أنابيب بيانات مشفرة، معالجة متوافقة مع GDPR، وبنية تحتية سحابية آمنة في جميع المناطق.", tr:"OAuth 2.0, şifreli veri hatları, GDPR uyumlu işleme ve tüm bölgelerde güvenli bulut altyapısı.", fa:"OAuth 2.0، خطوط لوله داده رمزنگاری‌شده، پردازش سازگار با GDPR و زیرساخت ابری امن در تمام مناطق." },

// ─────────────────────────────────────────────────────────────
// CTA
// ─────────────────────────────────────────────────────────────
cta_title: { en:"Ready to Transform Your Operations?", fr:"Prêt à Transformer Vos Opérations?", es:"¿Listo para Transformar Sus Operaciones?", ar:"هل أنت مستعد لتحويل عملياتك؟", tr:"Operasyonlarınızı Dönüştürmeye Hazır mısınız?", fa:"آماده‌اید عملیات خود را متحول کنید؟" },
cta_sub: { en:"Let's discuss how our AI-powered solutions can drive efficiency, reduce costs, and unlock new revenue streams for your business.", fr:"Discutons de la façon dont nos solutions IA peuvent améliorer l'efficacité, réduire les coûts et débloquer de nouvelles sources de revenus.", es:"Discutamos cómo nuestras soluciones con IA pueden impulsar la eficiencia, reducir costos y desbloquear nuevas fuentes de ingresos.", ar:"دعنا نناقش كيف يمكن لحلولنا المدعومة بالذكاء الاصطناعي تعزيز الكفاءة وخفض التكاليف وفتح مصادر دخل جديدة لعملك.", tr:"Yapay zeka destekli çözümlerimizin verimliliği nasıl artırabileceğini, maliyetleri nasıl azaltabileceğini ve yeni gelir akışlarını nasıl açabileceğini konuşalım.", fa:"بیایید درباره اینکه چگونه راه‌حل‌های مبتنی بر هوش مصنوعی ما می‌توانند بهره‌وری را افزایش، هزینه‌ها کاهش و جریان‌های درآمدی جدید باز کنند، گفتگو کنیم." },
cta_btn: { en:"Schedule a Consultation", fr:"Planifier une Consultation", es:"Programar una Consulta", ar:"حدد موعد استشارة", tr:"Danışma Planlayın", fa:"برنامه‌ریزی مشاوره" },

// ─────────────────────────────────────────────────────────────
// CONTACT SECTION
// ─────────────────────────────────────────────────────────────
con_tag: { en:"Get In Touch", fr:"Contactez-Nous", es:"Contáctenos", ar:"تواصل معنا", tr:"İletişime Geçin", fa:"تماس بگیرید" },
con_title: { en:"Start Your Project", fr:"Démarrez Votre Projet", es:"Inicie Su Proyecto", ar:"ابدأ مشروعك", tr:"Projenizi Başlatın", fa:"پروژه خود را شروع کنید" },
con_sub: { en:"Tell us about your needs and we'll design a tailored solution for your market.", fr:"Parlez-nous de vos besoins et nous concevrons une solution sur mesure pour votre marché.", es:"Cuéntenos sus necesidades y diseñaremos una solución a medida para su mercado.", ar:"أخبرنا باحتياجاتك وسنصمم حلاً مخصصاً لسوقك.", tr:"İhtiyaçlarınızı anlatın, pazarınız için özel bir çözüm tasarlayalım.", fa:"نیازهای خود را بگویید و ما یک راه‌حل سفارشی برای بازار شما طراحی خواهیم کرد." },
con_info_title: { en:"EDGE Global Solutions", fr:"EDGE Global Solutions", es:"EDGE Global Solutions", ar:"EDGE Global Solutions", tr:"EDGE Global Solutions", fa:"EDGE Global Solutions" },
con_info_desc: { en:"Operating across six continents with local expertise and global technology infrastructure. Reach us through any channel.", fr:"Opérant sur six continents avec une expertise locale et une infrastructure technologique mondiale. Contactez-nous par tout canal.", es:"Operando en seis continentes con experiencia local e infraestructura tecnológica global. Contáctenos por cualquier canal.", ar:"نعمل عبر ست قارات بخبرة محلية وبنية تحتية تقنية عالمية. تواصل معنا عبر أي قناة.", tr:"Yerel uzmanlık ve küresel teknoloji altyapısıyla altı kıtada faaliyet gösteriyoruz. Herhangi bir kanaldan bize ulaşın.", fa:"ما با تخصص محلی و زیرساخت فناوری جهانی در شش قاره فعالیت می‌کنیم. از هر کانالی با ما تماس بگیرید." },
con_email_label: { en:"Email", fr:"Email", es:"Correo", ar:"البريد الإلكتروني", tr:"E-posta", fa:"ایمیل" },
con_tg_label: { en:"Telegram", fr:"Telegram", es:"Telegram", ar:"تيليجرام", tr:"Telegram", fa:"تلگرام" },
con_loc_label: { en:"Headquarters", fr:"Siège", es:"Sede", ar:"المقر الرئيسي", tr:"Merkez", fa:"دفتر مرکزی" },
con_loc_value: { en:"Ireland — Serving EU, ME, Africa, Americas", fr:"Irlande — Service EU, MO, Afrique, Amériques", es:"Irlanda — Sirviendo UE, ME, África, Américas", ar:"أيرلندا — نخدم أوروبا، الشرق الأوسط، أفريقيا، الأمريكتين", tr:"İrlanda — AB, MO, Afrika, Amerika'ya Hizmet", fa:"ایرلند — خدمت به اتحادیه اروپا، خاورمیانه، آفریقا، قاره آمریکا" },
con_hours_label: { en:"Response Time", fr:"Temps de Réponse", es:"Tiempo de Respuesta", ar:"وقت الاستجابة", tr:"Yanıt Süresi", fa:"زمان پاسخ" },
con_hours_value: { en:"Under 24 hours — AI agents never sleep", fr:"Moins de 24 heures — les agents IA ne dorment jamais", es:"Menos de 24 horas — los agentes IA nunca duermen", ar:"أقل من 24 ساعة — وكلاء الذكاء الاصطناعي لا ينامون أبداً", tr:"24 saatten kısa — yapay zeka ajanları asla uyumaz", fa:"کمتر از ۲۴ ساعت — عامل‌های هوش مصنوعی هرگز نمی‌خوابند" },
form_name: { en:"Full Name", fr:"Nom Complet", es:"Nombre Completo", ar:"الاسم الكامل", tr:"Ad Soyad", fa:"نام کامل" },
form_name_ph: { en:"Your full name", fr:"Votre nom complet", es:"Su nombre completo", ar:"اسمك الكامل", tr:"Adınız ve soyadınız", fa:"نام کامل شما" },
form_email: { en:"Email Address", fr:"Adresse Email", es:"Correo Electrónico", ar:"عنوان البريد الإلكتروني", tr:"E-posta Adresi", fa:"آدرس ایمیل" },
form_email_ph: { en:"you@company.com", fr:"vous@entreprise.com", es:"tu@empresa.com", ar:"you@company.com", tr:"siz@sirket.com", fa:"you@company.com" },
form_service: { en:"Service Interest", fr:"Service Souhaité", es:"Servicio de Interés", ar:"الخدمة المطلوبة", tr:"İlgilendiğiniz Hizmet", fa:"خدمت مورد نظر" },
form_select: { en:"Select a service area...", fr:"Sélectionnez un domaine...", es:"Seleccione un área...", ar:"اختر مجال الخدمة...", tr:"Bir hizmet alanı seçin...", fa:"یک حوزه خدماتی انتخاب کنید..." },
form_region: { en:"Your Region", fr:"Votre Région", es:"Su Región", ar:"منطقتك", tr:"Bölgeniz", fa:"منطقه شما" },
form_region_select: { en:"Select region...", fr:"Sélectionnez la région...", es:"Seleccione región...", ar:"اختر المنطقة...", tr:"Bölge seçin...", fa:"منطقه را انتخاب کنید..." },
form_budget: { en:"Budget Range", fr:"Budget", es:"Presupuesto", ar:"الميزانية", tr:"Bütçe Aralığı", fa:"محدوده بودجه" },
form_budget_select: { en:"Select range...", fr:"Sélectionnez...", es:"Seleccione rango...", ar:"اختر النطاق...", tr:"Aralık seçin...", fa:"محدوده را انتخاب کنید..." },
form_message: { en:"Project Details", fr:"Détails du Proyecto", es:"Detalles del Proyecto", ar:"تفاصيل المشروع", tr:"Proje Detayları", fa:"جزئیات پروژه" },
form_message_ph: { en:"Tell us about your project, timeline, and specific requirements...", fr:"Parlez-nous de votre projet, calendrier et exigences spécifiques...", es:"Cuéntenos sobre su proyecto, cronograma y requisitos específicos...", ar:"أخبرنا عن مشروعك والجدول الزمني والمتطلبات المحددة...", tr:"Projeniz, zaman çizelgeniz ve özel gereksinimleriniz hakkında bilgi verin...", fa:"درباره پروژه، جدول زمانی و الزامات خاص خود بگویید..." },
form_submit: { en:"Send Inquiry", fr:"Envoyer la Demande", es:"Enviar Consulta", ar:"إرسال الاستفسار", tr:"Sorgu Gönder", fa:"ارسال درخواست" },

// ─────────────────────────────────────────────────────────────
// FOOTER
// ─────────────────────────────────────────────────────────────
footer_brand: { en:"AI-powered automation, drone surveying, sensor technology and digital transformation. Serving businesses across EU, Middle East, Africa, South America, Turkey and Iran.", fr:"Automatisation IA, lev topographique par drone, technologie de capteurs et transformation numérique. Au service des entreprises en UE, MO, Afrique, Amérique du Sud, Turquie et Iran.", es:"Automatización con IA, topografía con drones, tecnología de sensores y transformación digital. Sirviendo a empresas en UE, Medio Oriente, África, Sudamérica, Turquía e Irán.", ar:"أتمتة بالذكاء الاصطناعي، مسح بالطائرات بدون طيار، تقنية أجهزة الاستشعار والتحول الرقمي. نخدم الشركات في أوروبا والشرق الأوسط وأفريقيا وأمريكا الجنوبية وتركيا وإيران.", tr:"Yapay zeka destekli otomasyon, drone haritalama, sensör teknolojisi ve dijital dönüşüm. AB, Orta Doğu, Afrika, Güney Amerika, Türkiye ve İran'daki işletmelere hizmet.", fa:"اتوماسیون مبتنی بر هوش مصنوعی، نقشه‌برداری پهپادی، فناوری حسگر و تحول دیجیتال. خدمت به کسب‌وکارها در اتحادیه اروپا، خاورمیانه، آفریقا، آمریکای جنوبی، ترکیه و ایران." },
footer_svc: { en:"Services", fr:"Services", es:"Servicios", ar:"الخدمات", tr:"Hizmetler", fa:"خدمات" },
footer_markets: { en:"Markets", fr:"Marchés", es:"Mercados", ar:"الأسواق", tr:"Pazarlar", fa:"بازارها" },
footer_company: { en:"Company", fr:"Entreprise", es:"Empresa", ar:"الشركة", tr:"Şirket", fa:"شرکت" },
footer_about: { en:"About Us", fr:"À Propos", es:"Sobre Nosotros", ar:"من نحن", tr:"Hakkımızda", fa:"درباره ما" },
footer_careers: { en:"Careers", fr:"Carrières", es:"Carreras", ar:"وظائف", tr:"Kariyer", fa:"فرصت شغلی" },
footer_privacy: { en:"Privacy Policy", fr:"Politique de Confidentialité", es:"Política de Privacidad", ar:"سياسة الخصوصية", tr:"Gizlilik Politikası", fa:"سیاست حریم خصوصی" },
footer_terms: { en:"Terms of Service", fr:"Conditions d'Utilisation", es:"Términos de Servicio", ar:"شروط الخدمة", tr:"Hizmet Şartları", fa:"شرایط خدمات" },
footer_copy: { en:"© 2026 EDGE Global Solutions. All rights reserved.", fr:"© 2026 EDGE Global Solutions. Tous droits réservés.", es:"© 2026 EDGE Global Solutions. Todos los derechos reservados.", ar:"© 2026 EDGE Global Solutions. جميع الحقوق محفوظة.", tr:"© 2026 EDGE Global Solutions. Tüm hakları saklıdır.", fa:"© ۲۰۲۶ EDGE Global Solutions. تمامی حقوق محفوظ است." }
};

// Merge into main translations object
if (typeof translations !== 'undefined') {
    Object.assign(translations, translations_p2);
}
