#!/usr/bin/env python3
"""
EDGE Smart Video — Professional Video Slideshow
Text-first, branded video slideshow with real content generated by LLM.
No reliance on unreliable AI image APIs.

Usage:
  python3 compose_video.py --slides ./output/slides.json --output-dir ./output

  --slides JSON file with an array of slide objects:
    [
      {"type": "title|content|cta", "headline": "...", "bullets": ["..."], "subtitle": "..."}
    ]
"""

import json
import os
import sys
import html as html_mod


BRAND = {
    "bg": "#f0f4f0",         # Light green-gray background
    "surface": "#ffffff",     # White card surface
    "primary": "#1a7a3a",     # Professional deep green
    "primary_dim": "#145c2d", # Darker green for gradients
    "text": "#1e293b",        # Slate-800 near-black text
    "text_dim": "#64748b",    # Slate-500 medium gray
    "accent": "#d97706",      # Amber-600 accent for CTA contrast
    "font": "'Inter', 'Helvetica Neue', Arial, sans-serif"
}


def build_video_html(topic, sector, slides, output_dir, background_image=None):
    """Create a professional auto-advancing video-style slideshow."""
    slides_data = json.dumps(slides)
    bg_style = ""
    if background_image and os.path.exists(background_image):
        import base64
        with open(background_image, "rb") as f:
            img = base64.b64encode(f.read()).decode()
        bg_style = f"""
        body::before {{
            content: '';
            position: fixed;
            inset: 0;
            background: url('data:image/jpeg;base64,{img}') center/cover no-repeat;
            opacity: 0.08;
            z-index: 0;
        }}
        """

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>EDGE | {html_mod.escape(topic)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;800&display=swap" rel="stylesheet">
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
    background: {BRAND['bg']};
    font-family: {BRAND['font']};
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
    overflow: hidden;
}}
{bg_style}
.player {{
    width: 100%;
    max-width: 960px;
    aspect-ratio: 16/9;
    background: {BRAND['surface']};
    position: relative;
    overflow: hidden;
    border-radius: 16px;
    box-shadow:
        0 0 0 1px rgba(26, 122, 58, 0.1),
        0 30px 80px rgba(0, 0, 0, 0.6);
    z-index: 1;
}}

/* Progress bar */
.progress-bar {{
    position: absolute;
    top: 0; left: 0; right: 0;
    height: 3px;
    background: rgba(0,0,0,0.04);
    z-index: 100;
}}
.progress-fill {{
    height: 100%;
    background: linear-gradient(90deg, {BRAND['primary']}, {BRAND['primary_dim']});
    transition: width 0.1s linear;
    width: 0%;
}}

/* Slides */
.slide {{
    position: absolute;
    inset: 0;
    display: flex;
    flex-direction: column;
    opacity: 0;
    transition: opacity 0.6s ease, transform 0.6s ease;
    transform: scale(0.97);
    padding: 60px 80px;
}}
.slide.active {{
    opacity: 1;
    transform: scale(1);
}}

/* Brand watermark */
.brand-watermark {{
    position: absolute;
    top: 24px;
    left: 32px;
    z-index: 50;
    display: flex;
    align-items: center;
    gap: 10px;
}}
.brand-dot {{
    width: 8px; height: 8px;
    border-radius: 50%;
    background: {BRAND['primary']};
}}
.brand-name {{
    color: {BRAND['primary']};
    font-size: 11px;
    font-weight: 600;
    letter-spacing: 3px;
    text-transform: uppercase;
    opacity: 0.6;
}}

/* Title slide */
.slide-title {{
    justify-content: center;
    align-items: center;
    text-align: center;
}}
.slide-title .sector-tag {{
    color: {BRAND['primary']};
    font-size: clamp(12px, 1.4vw, 18px);
    font-weight: 600;
    letter-spacing: 6px;
    text-transform: uppercase;
    margin-bottom: 24px;
    opacity: 0;
    animation: fadeUp 0.6s 0.2s forwards;
}}
.slide-title h1 {{
    color: {BRAND['text']};
    font-size: clamp(28px, 4vw, 56px);
    font-weight: 800;
    line-height: 1.15;
    max-width: 800px;
    margin: 0 auto 20px;
    opacity: 0;
    animation: fadeUp 0.6s 0.4s forwards;
}}
.slide-title .subtitle {{
    color: {BRAND['text_dim']};
    font-size: clamp(14px, 1.5vw, 22px);
    font-weight: 300;
    opacity: 0;
    animation: fadeUp 0.6s 0.6s forwards;
}}
.slide-title .tagline-bar {{
    margin-top: 32px;
    width: 60px;
    height: 2px;
    background: {BRAND['primary']};
    margin-left: auto;
    margin-right: auto;
    opacity: 0;
    animation: fadeUp 0.6s 0.8s forwards;
}}

/* Content slide */
.slide-content {{
    justify-content: center;
}}
.slide-content .slide-header {{
    margin-bottom: 32px;
}}
.slide-content .slide-number {{
    color: {BRAND['primary']};
    font-size: 12px;
    font-weight: 700;
    letter-spacing: 4px;
    text-transform: uppercase;
    opacity: 0.5;
    margin-bottom: 6px;
}}
.slide-content h2 {{
    color: {BRAND['text']};
    font-size: clamp(22px, 2.8vw, 40px);
    font-weight: 700;
    line-height: 1.2;
    position: relative;
    padding-bottom: 16px;
}}
.slide-content h2::after {{
    content: '';
    position: absolute;
    bottom: 0; left: 0;
    width: 50px;
    height: 3px;
    background: {BRAND['primary']};
    border-radius: 2px;
}}
.slide-content .bullets {{
    margin-top: 28px;
    list-style: none;
    display: flex;
    flex-direction: column;
    gap: 14px;
}}
.slide-content .bullets li {{
    color: {BRAND['text_dim']};
    font-size: clamp(13px, 1.3vw, 20px);
    line-height: 1.5;
    padding-left: 28px;
    position: relative;
    opacity: 0;
    animation: fadeUp 0.4s forwards;
}}
.slide-content .bullets li::before {{
    content: '';
    position: absolute;
    left: 0;
    top: 10px;
    width: 10px;
    height: 10px;
    border: 2px solid {BRAND['primary']};
    border-radius: 50%;
    opacity: 0.6;
}}
.slide-content .bullets li:nth-child(1) {{ animation-delay: 0.2s; }}
.slide-content .bullets li:nth-child(2) {{ animation-delay: 0.35s; }}
.slide-content .bullets li:nth-child(3) {{ animation-delay: 0.5s; }}
.slide-content .bullets li:nth-child(4) {{ animation-delay: 0.65s; }}

/* CTA slide */
.slide-cta {{
    justify-content: center;
    align-items: center;
    text-align: center;
}}
.slide-cta h2 {{
    color: {BRAND['text']};
    font-size: clamp(24px, 3vw, 44px);
    font-weight: 800;
    margin-bottom: 16px;
    opacity: 0;
    animation: fadeUp 0.6s 0.2s forwards;
}}
.slide-cta .cta-url {{
    color: {BRAND['primary']};
    font-size: clamp(18px, 2vw, 32px);
    font-weight: 700;
    letter-spacing: 2px;
    opacity: 0;
    animation: fadeUp 0.6s 0.5s forwards;
}}
.slide-cta .cta-sub {{
    color: {BRAND['text_dim']};
    font-size: clamp(11px, 1vw, 16px);
    margin-top: 20px;
    letter-spacing: 3px;
    text-transform: uppercase;
    opacity: 0;
    animation: fadeUp 0.6s 0.8s forwards;
    opacity: 0.4;
}}

/* Navigation */
.nav {{
    position: absolute;
    bottom: 24px;
    left: 50%;
    transform: translateX(-50%);
    z-index: 50;
    display: flex;
    gap: 8px;
    align-items: center;
}}
.nav-dot {{
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background: rgba(0,0,0,0.1);
    cursor: pointer;
    transition: all 0.3s;
    border: none;
}}
.nav-dot.active {{
    background: {BRAND['primary']};
    box-shadow: 0 0 12px rgba(26, 122, 58, 0.4);
    width: 24px;
    border-radius: 4px;
}}

/* Animations */
@keyframes fadeUp {{
    from {{ opacity: 0; transform: translateY(20px); }}
    to {{ opacity: 1; transform: translateY(0); }}
}}

/* Responsive */
@media (max-width: 640px) {{
    .slide {{ padding: 32px 24px; }}
}}
</style>
</head>
<body>
<div class="player" id="player" tabindex="0">
    <div class="progress-bar"><div class="progress-fill" id="progressFill"></div></div>
    <div class="brand-watermark">
        <div class="brand-dot"></div>
        <div class="brand-name">EDGE Engineers</div>
    </div>
    <div id="slidesContainer"></div>
    <div class="nav" id="nav"></div>
</div>

<script>
const slides = {slides_data};
const SLIDE_DURATION = 5000;
let current = 0;
let timer = null;
let progressInterval = null;

function render() {{
    const container = document.getElementById('slidesContainer');
    const nav = document.getElementById('nav');
    container.innerHTML = '';
    nav.innerHTML = '';

    slides.forEach((slide, i) => {{
        const div = document.createElement('div');
        div.className = 'slide' + (i === current ? ' active' : '');

        if (slide.type === 'title') {{
            div.className += ' slide-title';
            div.innerHTML = `
                <div class="sector-tag">${{slide.sector || '{html_mod.escape(sector)}'}}</div>
                <h1>${{slide.headline}}</h1>
                ${{slide.subtitle ? `<div class="subtitle">${{slide.subtitle}}</div>` : ''}}
                <div class="tagline-bar"></div>
            `;
        }} else if (slide.type === 'cta') {{
            div.className += ' slide-cta';
            div.innerHTML = `
                <h2>${{slide.headline}}</h2>
                <div class="cta-url">${{slide.url || 'www.edgeengineers.net'}}</div>
                ${{slide.subtitle ? `<div class="cta-sub">${{slide.subtitle}}</div>` : ''}}
            `;
        }} else {{
            div.className += ' slide-content';
            const bullets = (slide.bullets || []).map(b => `<li>${{b}}</li>`).join('');
            div.innerHTML = `
                <div class="slide-header">
                    <div class="slide-number">${{slide.number || (i + 1)}} / ${{slides.length}}</div>
                    <h2>${{slide.headline}}</h2>
                </div>
                ${{bullets ? `<ul class="bullets">${{bullets}}</ul>` : ''}}
            `;
        }}

        container.appendChild(div);

        const dot = document.createElement('button');
        dot.className = 'nav-dot' + (i === current ? ' active' : '');
        dot.onclick = () => goTo(i);
        nav.appendChild(dot);
    }});
}}

function goTo(i) {{
    current = i;
    render();
    resetTimer();
}}

function next() {{
    current = (current + 1) % slides.length;
    render();
    resetTimer();
}}

function resetTimer() {{
    if (timer) clearInterval(timer);
    if (progressInterval) clearInterval(progressInterval);
    timer = setInterval(next, SLIDE_DURATION);
    updateProgress();
}}

function updateProgress() {{
    const bar = document.getElementById('progressFill');
    let start = Date.now();
    if (progressInterval) clearInterval(progressInterval);
    progressInterval = setInterval(() => {{
        const elapsed = Date.now() - start;
        const pct = Math.min((elapsed / SLIDE_DURATION) * 100, 100);
        bar.style.width = pct + '%';
    }}, 50);
}}

// Keyboard controls
document.getElementById('player').onkeydown = (e) => {{
    if (e.key === 'ArrowRight') next();
    if (e.key === 'ArrowLeft') goTo((current - 1 + slides.length) % slides.length);
}};

render();
resetTimer();
</script>
</body>
</html>"""

    output_path = os.path.join(output_dir, "video.html")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    print(f"  \u2713 Video slideshow: {output_path} ({os.path.getsize(output_path) // 1024}KB)")
    return output_path


def generate_slides(topic, sector, post_text):
    """Parse the LinkedIn post into structured slide content.
    This is the fallback if no slides.json is provided.
    """
    # Try to extract key points from the post for slide content
    paragraphs = [p.strip() for p in post_text.split('\n') if p.strip() and not p.startswith('http') and not p.startswith('#')]

    # Check if post has bullets (• or - or numbers)
    bullet_items = [p for p in paragraphs if p.startswith('•') or p.startswith('-') or p.startswith('  ')]
    content_paragraphs = [p for p in paragraphs if not p.startswith('•') and not p.startswith('-')]

    slides = [
        {
            "type": "title",
            "headline": topic,
            "subtitle": f"{sector} | EDGE Engineers",
            "sector": sector
        }
    ]

    # Problem slide
    problem_bullets = []
    if len(content_paragraphs) >= 2:
        problem_bullets = [content_paragraphs[1][:120]]
    if bullet_items:
        problem_bullets = bullet_items[:3]
    if not problem_bullets:
        problem_bullets = [f"Industry challenge in {sector} requiring innovative solutions"]

    slides.append({
        "type": "content",
        "headline": "The Challenge",
        "bullets": problem_bullets[:3]
    })

    # Solution slide
    solution_bullets = []
    for p in content_paragraphs[2:4] if len(content_paragraphs) > 2 else content_paragraphs[-2:]:
        solution_bullets.append(p[:120])
    while len(solution_bullets) < 2:
        solution_bullets.append(f"EDGE Engineers delivers cutting-edge {sector} solutions")
    if len(solution_bullets) > 3:
        solution_bullets = solution_bullets[:3]

    slides.append({
        "type": "content",
        "headline": "The EDGE Solution",
        "bullets": solution_bullets
    })

    # CTA slide
    slides.append({
        "type": "cta",
        "headline": "Ready to transform your operations?",
        "url": "www.edgeengineers.net",
        "subtitle": "ESA Incubatee | MaynoothWorks, Co. Kildare"
    })

    return slides


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Compose EDGE professional video slideshow")
    parser.add_argument("--slides", help="Path to slides.json (LLM-generated slide content)")
    parser.add_argument("--output-dir", default="./output", help="Output directory")
    parser.add_argument("--topic", required=True, help="Video topic")
    parser.add_argument("--sector", required=True, help="Industry sector")
    parser.add_argument("--post-text", default="", help="LinkedIn post text (for auto-generating slides)")
    parser.add_argument("--background", help="Optional background image path")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    # Load or generate slides
    if args.slides and os.path.exists(args.slides):
        with open(args.slides) as f:
            slides = json.load(f)
        print(f"  Loaded {len(slides)} slides from {args.slides}")
    else:
        slides = generate_slides(args.topic, args.sector, args.post_text)
        print(f"  Auto-generated {len(slides)} slides from post text")

    # Save slides for reference
    slides_path = os.path.join(args.output_dir, "slides.json")
    with open(slides_path, "w") as f:
        json.dump(slides, f, indent=2)
    print(f"  Saved slide data: {slides_path}")

    # Build video
    video_path = build_video_html(
        args.topic, args.sector, slides,
        args.output_dir, args.background
    )

    # Result manifest
    result = {
        "video_path": video_path,
        "slide_count": len(slides),
        "topic": args.topic,
        "sector": args.sector,
        "auto_generated": args.slides is None
    }

    result_path = os.path.join(args.output_dir, "video_result.json")
    with open(result_path, "w") as f:
        json.dump(result, f, indent=2)

    print(f"\n  \u2713 Video slideshow ready")
    print(f"  Open: {video_path}")
    print(f"  Slides: {len(slides)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
